-- CreateTable
CREATE TABLE "hello1" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "test" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "BOMBOCLATTTT" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "amen" TEXT NOT NULL
);
